### ISSUE TITLE
How do i add a packlet?

### ISSUE THREAD

**Issue by TJCgames** [VanillaTweaks/packs#1]
I have an idea for a texture packlet for Vanilla Tweaks. Can you help me add it?

I haven't got the full pack yet, but here's some base textures
[New Piskel.zip](https://github.com/VanillaTweaks/packs/files/9206982/New.Piskel.zip)

**Comment by GrantGryczan** [comment]
This repo isn't quite ready for public contributions yet, sorry. We're still in early development.

**Comment by TJCgames** [comment]
ok
i dont know how to change textures of sheep, leather armour or beds per colour yet
