### ISSUE TITLE
todo: Portal Stitching

### ISSUE THREAD

**Issue by PainfulPaladins** [VanillaTweaks/packs#2]
If you squint hard enough you can see a gap
Showcase:

![image](https://github.com/VanillaTweaks/packs/assets/122171814/9cae7231-1602-4be6-909c-f62437afe8df)

**Comment by GrantGryczan** [comment]
I'm confused, it seems you closed your own issue with no comment. And also Vanilla Tweaks has nothing to do with this.

**Comment by PainfulPaladins** [comment]
i edited the comment, turns out the portal looks that way because i was hovering over the block, sorry
